name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["feature", "enhancement"]
type: feature
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! We'd love to hear your ideas.
  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Describe the problem this feature would solve
      placeholder: "I find it difficult to..."
    validations:
      required: true
  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How should this feature work?
      placeholder: "The CLI should..."
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Other approaches you've considered
    validations:
      required: false
  - type: input
    id: platforms
    attributes:
      label: Relevant Platforms
      description: Which platforms would benefit? (macOS, Linux, Windows, all)
      placeholder: "all"
    validations:
      required: false
